version: '2.0'
services:
  mysql:
    image: mysql:5.7
    container_name: aol.mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
      - MYSQL_DATABASE=assistant_on_law
    volumes:
      - ./.data:/var/lib/mysql:rw
      - ./docs/mysql:/docker-entrypoint-initdb.d:ro
  redis:
    image: redis
    container_name: aol.redis
  backend:
    build: ./src/backend
    container_name: aol.backend
    links:
      - mysql
      - redis
    volumes:
      - ./config/config.yaml:/config/config.yaml
      - ./fake-cdn:/data/cdn:rw
  gateway:
    container_name: aol.gateway
    build: .
    ports:
      - 80:80
    volumes:
      - ./fake-cdn:/data/cdn:ro
      - ./www:/data/www:ro
    links:
      - backend
  gateway.dev:
    container_name: aol.gateway.dev
    build: .
    links:
      - backend
    ports:
      - 80:80
    volumes:
      - ./fake-cdn:/data/cdn:ro
      - ./src/frontend/entries:/data/www:ro


