version: '2.0'
services:
  gateway:
    image: gateway
    build: .
    ports:
      - 80:80
#    tty: true
    volumes:
      - ./fake-cdn:/data/cdn:ro
#    links:
#      - mysql
#      - redis
#    environment:
#      - CONFIG=/configs/go.yaml
  gateway.dev:
    image: gateway.dev
    build: .
    ports:
      - 80:80
    volumes:
      - ./fake-cdn:/data/cdn:ro
      - ./src/frontend/entries:/data/www:ro


