version: '2.0'
services:
  gateway:
    image: gateway
    build: .
    ports:
      - 80:80
#    tty: true
#    volumes:
#      - ./configs/sample:/configs
#      - ./static:/static/root
#    links:
#      - mysql
#      - redis
#    environment:
#      - CONFIG=/configs/go.yaml
